import { useState } from "react";
import { Check, ChevronLeft, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Dialog,DialogContent,DialogDescription,DialogHeader,DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";

type Form = {name:string;email:string;phone:string;city:string;housing:string;tenure:string;otherPets:string;children:string;motivation:string;experience:string;availability:string};
const initial:Form={name:"",email:"",phone:"",city:"",housing:"",tenure:"",otherPets:"",children:"",motivation:"",experience:"",availability:""};
export function AdoptionForm({open,onOpenChange,petName}:{open:boolean;onOpenChange:(v:boolean)=>void;petName:string}){const[step,setStep]=useState(1);const[form,setForm]=useState(initial);const[errors,setErrors]=useState<string[]>([]);const[done,setDone]=useState(false);const update=(key:keyof Form,value:string)=>setForm(v=>({...v,[key]:value}));
 const next=()=>{const required=step===1?["name","email","phone","city"]:step===2?["housing","tenure","otherPets","children"]:["motivation","experience","availability"];const missing=required.filter(k=>!form[k as keyof Form].trim());if(step===1&&!/^\S+@\S+\.\S+$/.test(form.email))missing.push("valid email");setErrors(missing);if(!missing.length)setStep(v=>Math.min(4,v+1));};
 const close=(v:boolean)=>{onOpenChange(v);if(!v)setTimeout(()=>{setStep(1);setDone(false);setErrors([])},200)};
 return <Dialog open={open} onOpenChange={close}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><span className="mb-2 w-fit rounded-full bg-secondary px-3 py-1 text-xs font-bold text-secondary-foreground">DEMO APPLICATION</span><DialogTitle className="font-display text-2xl">Adopt {petName}</DialogTitle><DialogDescription>This information stays in your browser and is never sent.</DialogDescription></DialogHeader>{done?<div className="py-10 text-center"><div className="mx-auto grid size-16 place-items-center rounded-full bg-teal text-teal-foreground"><Check className="size-8"/></div><h3 className="mt-5 font-display text-3xl font-bold">Demo complete</h3><p className="mx-auto mt-3 max-w-md text-muted-foreground">No real application was submitted. In a real adoption, the rescue organization would review your information and contact you.</p><Button className="mt-6" onClick={()=>close(false)}>Close</Button></div>:<><div className="grid grid-cols-4 gap-2">{[1,2,3,4].map(n=><div key={n} className="space-y-1"><div className={`h-1.5 rounded-full ${n<=step?"bg-primary":"bg-muted"}`}/><span className="text-[11px] text-muted-foreground">{n===1?"About you":n===2?"Your home":n===3?"Motivation":"Review"}</span></div>)}</div>
 <div className="min-h-72 py-3">{step===1&&<div className="grid gap-4 sm:grid-cols-2">{[["name","Full name"],["email","Email"],["phone","Phone"],["city","City"]].map(([k,l])=><div key={k}><Label htmlFor={k}>{l}</Label><Input id={k} className="mt-2" value={form[k as keyof Form]} onChange={e=>update(k as keyof Form,e.target.value)}/></div>)}</div>}{step===2&&<div className="grid gap-4 sm:grid-cols-2">{[["housing","Housing type"],["tenure","Own or rent?"],["otherPets","Other pets?"],["children","Children at home?"]].map(([k,l])=><div key={k}><Label htmlFor={k}>{l}</Label><Input id={k} className="mt-2" value={form[k as keyof Form]} onChange={e=>update(k as keyof Form,e.target.value)}/></div>)}</div>}{step===3&&<div className="grid gap-4">{[["motivation","Why do you want to adopt?"],["experience","Previous pet experience"],["availability","Daily availability"]].map(([k,l])=><div key={k}><Label htmlFor={k}>{l}</Label><Textarea id={k} className="mt-2" value={form[k as keyof Form]} onChange={e=>update(k as keyof Form,e.target.value)}/></div>)}</div>}{step===4&&<div className="rounded-xl bg-secondary p-5"><h3 className="font-bold">Please review your demo information</h3><dl className="mt-4 grid gap-3 text-sm sm:grid-cols-2">{Object.entries(form).map(([k,v])=><div key={k}><dt className="capitalize text-muted-foreground">{k.replace(/([A-Z])/g," $1")}</dt><dd className="font-medium">{v}</dd></div>)}</dl></div>}</div>
 {errors.length>0&&<p className="text-sm font-medium text-destructive">Please complete all fields with valid information.</p>}<div className="flex justify-between gap-3"><Button variant="outline" disabled={step===1} onClick={()=>setStep(v=>v-1)}><ChevronLeft/>Back</Button>{step<4?<Button onClick={next}>Next<ChevronRight/></Button>:<Button onClick={()=>setDone(true)}>Complete demo</Button>}</div></>}</DialogContent></Dialog>}
