/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as PetsRouteImport } from './routes/pets'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as PetsIndexRouteImport } from './routes/pets/index'
import { Route as PetsPetIdRouteImport } from './routes/pets.$petId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsRoute = PetsRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const PetsIndexRoute = PetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PetsRoute,
} as any)
const PetsPetIdRoute = PetsPetIdRouteImport.update({
  id: '/$petId',
  path: '/$petId',
  getParentRoute: () => PetsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/favorites': typeof FavoritesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pets': typeof PetsRouteWithChildren
  '/success-stories': typeof SuccessStoriesRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/': typeof PetsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/favorites': typeof FavoritesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets': typeof PetsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/donate': typeof DonateRoute
  '/favorites': typeof FavoritesRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pets': typeof PetsRouteWithChildren
  '/success-stories': typeof SuccessStoriesRoute
  '/pets/$petId': typeof PetsPetIdRoute
  '/pets/': typeof PetsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/donate'
    | '/favorites'
    | '/how-it-works'
    | '/pets'
    | '/success-stories'
    | '/pets/$petId'
    | '/pets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/donate'
    | '/favorites'
    | '/how-it-works'
    | '/success-stories'
    | '/pets/$petId'
    | '/pets'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/donate'
    | '/favorites'
    | '/how-it-works'
    | '/pets'
    | '/success-stories'
    | '/pets/$petId'
    | '/pets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DonateRoute: typeof DonateRoute
  FavoritesRoute: typeof FavoritesRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PetsRoute: typeof PetsRouteWithChildren
  SuccessStoriesRoute: typeof SuccessStoriesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets': {
      id: '/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof PetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pets/': {
      id: '/pets/'
      path: '/'
      fullPath: '/pets/'
      preLoaderRoute: typeof PetsIndexRouteImport
      parentRoute: typeof PetsRoute
    }
    '/pets/$petId': {
      id: '/pets/$petId'
      path: '/$petId'
      fullPath: '/pets/$petId'
      preLoaderRoute: typeof PetsPetIdRouteImport
      parentRoute: typeof PetsRoute
    }
  }
}

interface PetsRouteChildren {
  PetsPetIdRoute: typeof PetsPetIdRoute
  PetsIndexRoute: typeof PetsIndexRoute
}

const PetsRouteChildren: PetsRouteChildren = {
  PetsPetIdRoute: PetsPetIdRoute,
  PetsIndexRoute: PetsIndexRoute,
}

const PetsRouteWithChildren = PetsRoute._addFileChildren(PetsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DonateRoute: DonateRoute,
  FavoritesRoute: FavoritesRoute,
  HowItWorksRoute: HowItWorksRoute,
  PetsRoute: PetsRouteWithChildren,
  SuccessStoriesRoute: SuccessStoriesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
